# Generated by Django 5.1.6 on 2025-04-12 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Статья блога', 'verbose_name_plural': 'Статьи блога'},
        ),
        migrations.AlterModelOptions(
            name='calculation',
            options={'verbose_name': 'Расчет', 'verbose_name_plural': 'Расчеты'},
        ),
        migrations.AlterModelOptions(
            name='chatlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог чата', 'verbose_name_plural': 'Логи чата'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Проект портфолио', 'verbose_name_plural': 'Проекты портфолио'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='area',
            field=models.FloatField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='include_materials',
            field=models.BooleanField(default=False, verbose_name='Включить материалы'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость работы'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='material',
            field=models.CharField(max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость материалов'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='urgency',
            field=models.CharField(max_length=50, verbose_name='Срочность'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='work_type',
            field=models.CharField(max_length=100, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='audio_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к аудио'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='language',
            field=models.CharField(default='ru', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_after',
            field=models.ImageField(upload_to='portfolio/', verbose_name='Изображение после'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_before',
            field=models.ImageField(upload_to='portfolio/', verbose_name='Изображение до'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('construction', 'Строительство'), ('design', 'Дизайн'), ('renovation', 'Ремонт'), ('bathroom', 'Ванные комнаты'), ('electrical', 'Электрика'), ('facade', 'Фасады'), ('demolition', 'Демонтаж'), ('cleaning', 'Уборка')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
