# Generated by Django 5.1.6 on 2025-05-05 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='include_materials',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='urgency',
        ),
        migrations.AddField(
            model_name='calculation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='material_modifiers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Модификаторы материалов'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('apartment', 'Ремонт квартиры'), ('house', 'Ремонт дома'), ('office', 'Ремонт офиса'), ('warehouse', 'Ремонт склада'), ('facade', 'Фасадные работы'), ('bathroom', 'Ремонт ванной'), ('electrical', 'Электрика'), ('demolition', 'Демонтаж')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Базовая цена за м²'),
        ),
    ]
