# Generated by Django 5.1.6 on 2025-05-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_calculation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
