# Generated by Django 5.1.6 on 2025-03-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_calculation_end_date_calculation_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя партнера')),
                ('contact_info', models.CharField(max_length=255, verbose_name='Контактная информация')),
                ('referral_code', models.CharField(max_length=50, unique=True, verbose_name='Реферальный код')),
                ('total_referrals', models.IntegerField(default=0, verbose_name='Количество привлеченных клиентов')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий заработок')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
