# Generated by Django 5.1.6 on 2025-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_calculation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='material_modifiers',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='base_material_cost_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Базовая стоимость материалов за м²'),
        ),
        migrations.AddField(
            model_name='service',
            name='labor_cost_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Трудовые затраты за м²'),
        ),
    ]
