# Generated by Django 5.1.6 on 2025-05-20 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_service_material_modifiers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='area',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Площадь'),
        ),
    ]
